import test from 'node:test';import assert from 'node:assert/strict';import {loadApp} from './load-app.mjs';
const settle=()=>new Promise(r=>setImmediate(r));
function setup(){
 let foreground=true,locationListener=null,clock=100000,key=0,requests=0;const timers=new Map(),sent=[];
 const route={distance:'200',duration:'150',steps:[{instruction:'向东走',distance:'85',road:'合成路',polyline:'116.4,39.9;116.401,39.9'},{instruction:'向北走',distance:'110',road:'合成路',polyline:'116.401,39.9;116.401,39.901'}]};
 class Result {steps=[];distance='';duration='';}
 class Remote{cancel(){} async resolvePlace(){requests++;return '116.4,39.9';} async gpsCoordinate(c,lon,lat){requests++;return `${lon},${lat}`;} async routeCoordinates(){requests++;return structuredClone(route);}}
 const platform={'@kit.AbilityKit':{abilityAccessCtrl:{createAtManager:()=>({requestPermissionsFromUser:async()=>({authResults:[0,0]})})}},'@kit.LocationKit':{geoLocationManager:{LocationRequestPriority:{ACCURACY:1},LocationRequestScenario:{NAVIGATION:1},getCurrentLocation:async()=>({longitude:116.4,latitude:39.9,timeStamp:clock,accuracy:5}),on:(k,r,cb)=>locationListener=cb,off:()=>locationListener=null}},'./RemoteServices':{RemoteServices:Remote,RouteResult:Result,ServiceConfig:class{}},'./NavigationProgress':loadApp('NavigationProgress'),'./DeviceFeatures':{}};
 const features={displayActive:false,state:{connected:true,displayReady:false,display:'wait'},show:async(text,continuous)=>{sent.push({kind:'show',text,continuous});features.displayActive=true;features.state.displayReady=true;},updateDisplay:async text=>{sent.push({kind:'update',text});},stopDisplay:async()=>{sent.push({kind:'stop'});features.displayActive=false;features.state.displayReady=false;}};
 const globals={Date:class extends Date {static now(){return clock;}},setInterval:(f,n)=>{timers.set(++key,{f,n,interval:true});return key;},setTimeout:(f,n)=>{timers.set(++key,{f,n});return key;},clearInterval:id=>timers.delete(id),clearTimeout:id=>timers.delete(id)};
 const {NavigationSession}=loadApp('NavigationSession',platform,globals);const session=new NavigationSession(features,()=>foreground);
 return {session,features,sent,timers,platform,clock:()=>clock,requests:()=>requests,fix:fix=>locationListener?.(fix),hasLocation:()=>!!locationListener,background:()=>foreground=false,tick:async(ms=1000)=>{clock+=ms;for(const t of [...timers.values()])if(t.interval)t.f();await settle();},plan:async live=>session.plan({},'起点','终点','北京','walking',live,{})};
}
test('preview and simulator never register location; only explicit active session gets continuous display',async()=>{const s=setup();await s.plan(false);assert(!s.hasLocation());s.session.start({},true);await s.session.show();assert.equal(s.sent[0].continuous,true);await s.tick();assert(s.sent.some(r=>r.kind==='update'&&r.text.includes('模拟演示')));await s.session.stop();assert.equal(s.timers.size,0);assert.equal(s.sent.at(-1).kind,'stop');});
test('GPS mode registers location only after explicit start; stops on background and clears listeners',async()=>{const s=setup();await s.plan(true);assert(!s.hasLocation());s.session.start({},false);assert(s.hasLocation());await s.session.show();s.background();await s.tick();assert(!s.session.state.active);assert(!s.hasLocation());assert.equal(s.timers.size,0);assert.equal(s.sent.at(-1).kind,'stop');});
test('no fresh fix produces stale warning rather than old distance updates',async()=>{const s=setup();await s.plan(true);s.session.start({},false);await s.session.show();await s.tick(21000);assert(s.session.state.text.includes('定位信号中断'));await s.session.stop();});
test('inaccurate or old native fix never starts conversion or changes progress',async()=>{const s=setup();await s.plan(true);s.session.start({},false);const n=s.requests();s.fix({longitude:116.401,latitude:39.901,timeStamp:s.clock(),accuracy:100});s.fix({longitude:116.401,latitude:39.901,timeStamp:1,accuracy:5});await settle();assert.equal(s.requests(),n);await s.session.stop();});
test('cancellation during route lookup does not resurrect ready route',async()=>{const s=setup();let resolve;s.platform['./RemoteServices'].RemoteServices.prototype.resolvePlace=()=>new Promise(r=>resolve=r);const pending=s.plan(false);await settle();await s.session.stop();resolve('116.4,39.9');await pending;assert.equal(s.session.state.route.steps.length,0);assert(!s.session.state.busy);});
test('display open interrupted by stop cannot reclaim session ownership',async()=>{const s=setup();await s.plan(false);s.session.start({},true);let resolve;s.features.show=()=>new Promise(r=>resolve=r);const opening=s.session.show();await settle();await s.session.stop();resolve();await opening;assert.equal(s.sent.filter(r=>r.kind==='stop').length,1);assert.equal(s.timers.size,0);assert(!s.session.state.active);});
test('cancel while native location is pending never sends the late coordinates to provider',async()=>{const s=setup();let resolve;s.platform['@kit.LocationKit'].geoLocationManager.getCurrentLocation=()=>new Promise(r=>resolve=r);const planning=s.plan(true);await settle();await s.session.stop();resolve({longitude:116.4,latitude:39.9,timeStamp:s.clock(),accuracy:5});await planning;assert.equal(s.requests(),0);});
test('existing unrelated display is not claimed or closed by navigation',async()=>{const s=setup();await s.plan(false);s.features.displayActive=true;await assert.rejects(s.session.show(),/其他显示/);await s.session.stop();assert.equal(s.sent.length,0);});
