import test from 'node:test';import assert from 'node:assert/strict';import {loadApp} from './load-app.mjs';import {loadCore} from './load-core.mjs';
const {businessEnvelope}=loadCore('./BusinessCommands'),{readLauncherEnvelope}=loadCore('./LauncherStatus');const peer='aabbccddeeff';
function setup(){const sent=[],timers=new Map();let id=0,occupied=false,reject=false,callback;
 const {NotificationSession}=loadApp('NotificationSession',{'@kit.CryptoArchitectureKit':{cryptoFramework:{createRandom:()=>({generateRandomSync:n=>({data:new Uint8Array(n).fill(7)})})}}},{setTimeout:(f,ms)=>{timers.set(++id,{f,ms});return id;},clearTimeout:id=>timers.delete(id)});
 const session=new NotificationSession(async(b,p)=>{if(reject)throw Error('busy');const e=readLauncherEnvelope(p);sent.push({b,type:e.type,json:JSON.parse(new TextDecoder().decode(e.json)),length:p.length});if(callback)callback(e.type);},()=>peer,()=>!occupied);
 const receive=(type,j,from=peer)=>session.receive(from,businessEnvelope(type,new TextEncoder().encode(JSON.stringify(j))));return {session,sent,timers,receive,occupy:()=>occupied=true,fail:()=>reject=true,onSend:f=>callback=f};
}
test('manual notification requires explicit master; does not replace source or timing settings',async()=>{const s=setup();await assert.rejects(s.session.notify('a','b'));await s.session.setEnabled(true);assert.equal(s.sent[0].b,21);assert.equal(s.sent[0].type,18);assert.deepEqual(s.sent[0].json,{notification:true});await s.session.notify('通知测试','合成内容5826');const p=s.sent[1];assert.equal(p.type,2);assert.equal(p.json.appId,'org.turboio.harmony.research');assert.equal(p.json.reply,false);assert(/^[1-9][0-9]*$/.test(p.json.notificationUID));assert(/T\d{2}:\d{2}:\d{2}\.\d{3}$/.test(p.json.timestamp));assert(s.session.waiting);});
test('only same UID and peer status settle pending; early synchronous ACK is not overwritten',async()=>{const s=setup();await s.session.setEnabled(true);s.onSend(type=>{if(type===2)s.receive(3,{notificationUID:s.session.uid,state:1});});await s.session.notify('a','b');assert(!s.session.waiting);assert.match(s.session.note,/同 UID 回报/);s.onSend(()=>{});await s.session.notify('a','b');s.receive(3,{notificationUID:'wrong',state:1});s.receive(3,{notificationUID:s.session.uid,state:1},'other');assert(s.session.waiting);s.receive(3,{notificationUID:s.session.uid,state:3});assert(!s.session.waiting);assert.match(s.session.note,/勿扰/);});
test('timeout never retries and disconnect resets local grant',async()=>{const s=setup();await s.session.setEnabled(true);await s.session.notify('a','b');[...s.timers.values()][0].f();assert.equal(s.sent.length,2);assert(!s.session.waiting);s.session.disconnected();assert(!s.session.enabled);await assert.rejects(s.session.notify('a','b'));});
test('private ANCS, malformed frames and operation callbacks never trigger tools or additional sends',async()=>{const s=setup();await s.session.setEnabled(true);await s.session.notify('a','b');const n=s.sent.length;s.receive(1,{content:'not retained'});s.session.receive(peer,Uint8Array.of(255));s.receive(4,{notificationUID:s.session.uid,cmd:9});assert.equal(s.sent.length,n);assert(!s.session.note.includes('not retained'));s.receive(18,{notification:false});assert(!s.session.enabled);});
test('content bounds fit negotiated 512 MTU; occupied and failed calls do not claim success',async()=>{const s=setup();await s.session.setEnabled(true);await s.session.notify('题'.repeat(16),'文'.repeat(48));assert(s.sent.at(-1).length+10<=509);s.session.disconnected();await s.session.setEnabled(true);s.occupy();await assert.rejects(s.session.notify('a','b'));const f=setup();f.fail();await assert.rejects(f.session.setEnabled(true));assert(!f.session.enabled);});
