import test from 'node:test';import assert from 'node:assert/strict';import {loadApp} from './load-app.mjs';import {loadCore} from './load-core.mjs';
const {businessEnvelope}=loadCore('./BusinessCommands'),{readLauncherEnvelope}=loadCore('./LauncherStatus'),peer='aabbccddeeff';
const settle=()=>new Promise(r=>setImmediate(r));
const packet=(type,j,bytes=[])=>{const prefix=businessEnvelope(type,new TextEncoder().encode(JSON.stringify(j)));const n=bytes.length;return Uint8Array.from([...prefix,...(n?[34,...(n>127?[n%128|128,Math.floor(n/128)]:[n]),...bytes]:[])]);};
function setup(){
 const files=new Map(),dirs=new Set(),handles=new Map(),sent=[],timers=new Map();let fd=0,random=0,timer=0,connected=true,decodeFails=false;
 const fs={OpenMode:{CREATE:1,READ_WRITE:2,WRITE_ONLY:4,TRUNC:8},WhenceType:{SEEK_SET:0},accessSync:p=>files.has(p)||dirs.has(p),mkdirSync:p=>{if(dirs.has(p))throw Error('exists');dirs.add(p);},listFileSync:p=>[...dirs].filter(d=>d.startsWith(p+'/')&&!d.slice(p.length+1).includes('/')).map(d=>d.slice(p.length+1)),openSync:(path,flags)=>{if(!files.has(path)){if(!(flags&1))throw Error('missing');files.set(path,new Uint8Array());}if(flags&8)files.set(path,new Uint8Array());const file={fd:++fd,path,pos:0};handles.set(file.fd,file);return file;},closeSync:f=>handles.delete(typeof f==='number'?f:f.fd),lseek:(fd,pos)=>{handles.get(fd).pos=pos;return pos;},writeSync:(fd,buffer)=>{const h=handles.get(fd),b=new Uint8Array(buffer),old=files.get(h.path),out=new Uint8Array(Math.max(old.length,h.pos+b.length));out.set(old);out.set(b,h.pos);h.pos+=b.length;files.set(h.path,out);return b.length;},readSync:(fd,buffer,options={})=>{const h=handles.get(fd),b=files.get(h.path),n=Math.min(options.length??buffer.byteLength,b.length-h.pos);new Uint8Array(buffer).set(b.slice(h.pos,h.pos+n));h.pos+=n;return n;},fsyncSync:()=>{},renameSync:(a,b)=>{files.set(b,files.get(a));files.delete(a);},readTextSync:p=>new TextDecoder().decode(files.get(p)),statSync:p=>({size:files.get(typeof p==='number'?handles.get(p).path:p).length})};
 const {RecordingSession}=loadApp('RecordingSession',{'@kit.AbilityKit':{},'@kit.CoreFileKit':{fileIo:fs},'@kit.CryptoArchitectureKit':{cryptoFramework:{createRandom:()=>({generateRandomSync:n=>({data:new Uint8Array(n).fill(++random)})})}},'libturbo_audio.so':{recordingReset:()=>{},recordingClose:()=>{},recordingDecode:()=>{if(decodeFails)throw Error('bad');return new Uint8Array(1280).fill(1).buffer;}},'./RecordingCoverage':loadApp('RecordingCoverage')},{setTimeout:(f,ms)=>{timers.set(++timer,{f,ms});return timer;},clearTimeout:id=>timers.delete(id)});
 const session=new RecordingSession(async(b,p)=>{assert.equal(b,14);const e=readLauncherEnvelope(p);sent.push({type:e.type,body:JSON.parse(new TextDecoder().decode(e.json))});},()=>connected?peer:'',()=>true);session.initialize({filesDir:'/private-test'});
 return {session,sent,timers,files,handles,id:()=>sent.find(s=>s.type===1).body.uuid,failDecoder:()=>decodeFails=true,feed:async(type,j,b)=>{session.receive(peer,packet(type,j,b));await settle();},drain:async()=>{for(let n=0;n<6;n++){for(const [id,t]of [...timers])if(t.ms===0||t.ms===1000){timers.delete(id);t.f();}await settle();}}};
}
test('explicit start sends foreground first, prepares storage, and receives matching UUID only',async()=>{const s=setup();await s.session.start();assert.deepEqual(s.sent.map(x=>x.type),[14,1]);assert(s.files.size>=2);await s.feed(3,{uuid:'wrong',offset:0},new Uint8Array(240).fill(2));assert.equal(s.session.bytes,0);await s.feed(3,{uuid:s.id(),offset:0},new Uint8Array(240).fill(2));assert.equal(s.session.bytes,240);s.session.disconnected();assert.equal(s.handles.size,0);});
test('physical start with opt-in receives immediately queued audio without losing first packet',async()=>{const s=setup();await s.session.enable(true);s.session.receive(peer,packet(1,{uuid:'eye-test',action:1}));s.session.receive(peer,packet(3,{uuid:'eye-test',offset:0},new Uint8Array(240).fill(2)));await settle();assert.equal(s.session.bytes,240);assert.equal(s.sent.at(-1).body.action,2);s.session.disconnected();});
test('out of order identical chunks reconstruct exactly; successful completion produces stereo WAV',async()=>{const s=setup();await s.session.start();const id=s.id();await s.feed(3,{uuid:id,offset:240},new Uint8Array(240).fill(3));await s.feed(3,{uuid:id,offset:0},new Uint8Array(240).fill(2));await s.feed(3,{uuid:id,offset:240},new Uint8Array(240).fill(3));assert.equal(s.session.bytes,480);await s.feed(6,{uuid:id,completed:true});await s.drain();assert.equal(s.session.items.length,1);assert(s.session.items[0].complete);const raw=s.files.get(s.session.file(s.session.items[0],false)),wav=s.files.get(s.session.file(s.session.items[0],true));assert.equal(raw[0],2);assert.equal(raw[240],3);assert.equal(wav.length,44+2560);assert.equal(new DataView(wav.buffer).getUint16(22,true),2);assert.equal(s.handles.size,0);});
test('different overlapping bytes invalidate recording and preserve original bytes',async()=>{const s=setup();await s.session.start();const id=s.id();await s.feed(3,{uuid:id,offset:0},new Uint8Array(240).fill(2));await s.feed(3,{uuid:id,offset:0},new Uint8Array(240).fill(3));assert(!s.session.active);s.session.refresh();assert(!s.session.items[0].complete);assert.equal(s.files.get(s.session.file(s.session.items[0],false))[0],2);assert.equal(s.handles.size,0);});
test('completion with missing range or decoder error never publishes audio.wav',async()=>{for(const kind of ['gap','decode']){const s=setup();await s.session.start();const id=s.id();if(kind==='decode')s.failDecoder();await s.feed(3,{uuid:id,offset:kind==='gap'?240:0},new Uint8Array(240).fill(2));await s.feed(6,{uuid:id,completed:true});await s.drain();assert(![...s.files.keys()].some(p=>p.endsWith('/audio.wav')));assert.equal(s.handles.size,0);}});
test('late audio invalidates metadata and disables export even with a stale previously complete row',async()=>{const s=setup();await s.session.start();const id=s.id();await s.feed(3,{uuid:id,offset:0},new Uint8Array(240).fill(2));await s.feed(6,{uuid:id,completed:true});await s.drain();const old=s.session.items[0];assert(old.complete);await s.feed(3,{uuid:id,offset:240},new Uint8Array(240).fill(2));assert(!s.session.items[0].complete);assert.throws(()=>s.session.file(old,true));});
test('stop requires explicit completion; timeout preserves raw and never auto-uploads',async()=>{const s=setup();await s.session.start();await s.session.stop();assert(s.session.active);const timer=[...s.timers.values()].find(t=>t.ms===30000);timer.f();assert(!s.session.active);assert(s.files.size>=2);assert(s.sent.every(s=>[1,4,14].includes(s.type)));});
test('start timeout releases storage; matching start reply or actual audio clears the start deadline',async()=>{for(const mode of ['timeout','ack','audio']){const s=setup();await s.session.start();if(mode==='ack')await s.feed(1,{uuid:s.id(),action:2,code:1});if(mode==='audio')await s.feed(3,{uuid:s.id(),offset:0},new Uint8Array(240).fill(2));const t=[...s.timers.values()].find(t=>t.ms===10000);if(mode==='timeout'){assert(t);t.f();assert.equal(s.handles.size,0);assert(!s.session.active);}else{assert(!t);s.session.disconnected();}}});
test('reload refuses truncated WAV even when old metadata says complete',async()=>{const s=setup();await s.session.start();await s.feed(3,{uuid:s.id(),offset:0},new Uint8Array(240).fill(2));await s.feed(6,{uuid:s.id(),completed:true});await s.drain();const old=s.session.items[0],path=s.session.file(old,true);s.files.set(path,new Uint8Array(44));s.session.refresh();assert(!s.session.items[0].complete);assert.throws(()=>s.session.file(old,true));});
test('phone start includes official online mode and type; UI waits for actual ACK',async()=>{const s=setup();await s.session.start();const body=s.sent.find(row=>row.type===1).body;assert.equal(body.mode,1);assert.equal(body.type,1);assert.equal(body.action,1);assert(s.session.starting);await s.feed(1,{uuid:s.id(),action:2,code:1});assert(!s.session.starting);s.session.disconnected();});
test('same-session start request ACKs exact online profile without another directory; foreign UUID not adopted',async()=>{const s=setup();await s.session.start();const count=s.files.size;await s.feed(1,{uuid:s.id(),action:1,mode:1,type:1});assert.equal(s.files.size,count);assert.deepEqual(s.sent.at(-1).body,{uuid:s.id(),action:2,mode:1,code:1,type:1});const n=s.sent.length;await s.feed(1,{uuid:'foreign',action:1});assert.equal(s.sent.length,n);s.session.disconnected();});
