import test from 'node:test';import assert from 'node:assert/strict';import {loadApp} from './load-app.mjs';
const settle=()=>new Promise(r=>setImmediate(r)),{stereoWavHeader}=loadApp('RecordingCoverage');
function setup(){const pcm=new Uint8Array(6400),view=new DataView(pcm.buffer);for(let i=0;i<pcm.length;i+=4){view.setInt16(i,100,true);view.setInt16(i+2,300,true);}const wav=new Uint8Array(44+pcm.length);wav.set(stereoWavHeader(pcm.length));wav.set(pcm,44);
 let pos=0,closed=false,socket;const timers=new Map();let tid=0;
 const fs={OpenMode:{READ_ONLY:1},openSync:()=>({fd:1}),statSync:()=>({size:wav.length}),readSync:(fd,buffer)=>{const n=Math.min(buffer.byteLength,wav.length-pos);new Uint8Array(buffer).set(wav.slice(pos,pos+n));pos+=n;return n;},closeSync:()=>closed=true};
 const kits={'@kit.NetworkKit':{webSocket:{createWebSocket:()=>{const events={},sent=[];socket={events,sent,on:(key,f)=>events[key]=f,off:key=>delete events[key],connect:async(url,options)=>{socket.options=options;socket.url=url;return true;},send:async data=>{sent.push(typeof data==='string'?data:new Uint8Array(data).slice());return true;},close:async()=>true};return socket;}}},'@kit.CoreFileKit':{fileIo:fs},'@kit.BasicServicesKit':{},'@kit.CryptoArchitectureKit':{cryptoFramework:{createRandom:()=>({generateRandomSync:n=>({data:new Uint8Array(n).fill(1)})})}},'./RemoteServices':{}};
 const mod=loadApp('RecordingASR',kits,{setTimeout:(f,ms)=>{timers.set(++tid,{f,ms});return tid;},clearTimeout:id=>timers.delete(id)});
 const asr=new mod.RecordingASR(),config={asrKey:'synthetic-test',asrHost:'test.aliyuncs.com',asrModel:'qwen-audio-3.0-asr-flash-streaming'};
 const emit=(event,sentence,task='01'.repeat(16))=>socket.events.message?.(undefined,JSON.stringify({header:{event,task_id:task},payload:{output:{sentence}}}));
 return {asr,mod,config,emit,wav,socket:()=>socket,closed:()=>closed,timers,tick:async()=>{for(const [id,t]of [...timers])if(t.ms===100){timers.delete(id);t.f();}await settle();}};
}
test('stereo downmix averages both channels and preserves signed extremes',()=>{const s=setup(),a=new Uint8Array(8),v=new DataView(a.buffer);v.setInt16(0,-32768,true);v.setInt16(2,-32768,true);v.setInt16(4,0,true);v.setInt16(6,2000,true);const mono=s.mod.downmixStereo16(a),m=new DataView(mono.buffer);assert.equal(m.getInt16(0,true),-32768);assert.equal(m.getInt16(2,true),1000);assert.throws(()=>s.mod.downmixStereo16(new Uint8Array(3)));});
test('file ASR waits for whole-task finish after multiple VAD sentence endings and deduplicates sentence IDs',async()=>{const s=setup();let finished=false;const task=s.asr.transcribe('/synthetic.wav',s.config).then(text=>{finished=true;return text;});const socket=s.socket();assert.equal(socket.sent.length,0);socket.events.open();await settle();s.emit('task-started');await settle();const sent=socket.sent.find(d=>d instanceof Uint8Array);assert.equal(sent.length,3200);assert.equal(new DataView(sent.buffer).getInt16(0,true),200);s.emit('result-generated',{text:'第一句',sentence_end:true,sentence_id:0});s.emit('result-generated',{text:'第二句',sentence_end:true,sentence_id:1});s.emit('result-generated',{text:'第二句修订',sentence_end:true,sentence_id:1});await settle();assert(!finished);await s.tick();assert(socket.sent.some(d=>typeof d==='string'&&JSON.parse(d).header.action==='finish-task'));s.emit('task-finished');assert.equal(await task,'第一句\n第二句修订');assert(s.closed());assert.equal(socket.options.skipServerCertVerification,false);assert(!socket.url.includes(s.config.asrKey));});
test('cancel detaches network and closes file, stale messages cannot finish',async()=>{const s=setup();const task=s.asr.transcribe('/synthetic.wav',s.config);const reject=assert.rejects(task,/取消/);const old=s.socket().events.message;s.asr.cancel();old(undefined,JSON.stringify({header:{event:'task-finished',task_id:'01'.repeat(16)}}));await reject;assert(s.closed());assert(!s.asr.active);});
test('invalid WAV is rejected before creating external connection',async()=>{const s=setup();s.wav[22]=1;await assert.rejects(s.asr.transcribe('/synthetic.wav',s.config),/立体声/);assert.equal(s.socket(),undefined);assert(s.closed());});
test('no final text or premature task-finished never returns false success',async()=>{const s=setup();const task=s.asr.transcribe('/synthetic.wav',s.config);const rejected=assert.rejects(task,/有效文字/);s.emit('task-finished');await rejected;assert(s.closed());});
